### ISSUE TITLE
Urgent: Can not open place profile 2.2.3

### ISSUE THREAD

**Issue by OneMapCo** [TeamZoon/onemap_mobile_dev#142]
got this error

![img_3098](https://user-images.githubusercontent.com/35514520/39388730-8887e92a-4aac-11e8-8711-878820bd90fd.JPG)

**Comment by hbpoison** [comment]
Operation and maintenance failure report: This issue was leaded by an unexpected production migration of new Promotion model. This migration should be only applied to the development environment, but accidentally applied to production environment.
A patch of the production server already apply to resolve the issue.
Issue Opt-in time: 2018-4-27 21:37
Issue Opt-out time: 2018-4-28 8:35
Effected modules: Place Profile
Effected users: All user with version 2.0+
Data Loss: No
